import { MultiPolygon, Polygon, Feature, FeatureCollection } from 'geojson';
import { CRS } from "./_SharedTypes";

export interface NeighborhoodsCollection<
  G extends Polygon | MultiPolygon,
  P = NeighborhoodsFeatureProperties
> extends FeatureCollection<G, P> {
  type: 'FeatureCollection';
  features: NeighborhoodsFeature<G, P>[];
  crs: CRS;
}

export interface NeighborhoodsFeature<
  G extends Polygon | MultiPolygon,
  P = NeighborhoodsFeatureProperties
> extends Feature<G, P> {}
 

export interface __NeighborhoodsFeatureProperties {
  ////****** */
  area:number

  //**************/ */
  PERMITTER: Permitter;
  ID: number;
  PARENT_ZONE: number;
  COLOR: number;
  NAME: string;
  VERKEER?: number;
  WATER?: number;
  VERKEER_VERBLIJFSGEBIED?: number;
  TUIN?: number;
  WOONGEBIED?: number;
  GROEN?: number;
  WONEN?: number;
  AGRARISCH_MET_WAARDEN_LANDSCHAP?: number;
  WONEN_1?: number;
  RECREATIE_VOLKSTUIN?: number;
  WONEN_3?: number;
  NATUUR?: number;
  SPORT?: number;
  AGRARISCH_MET_WAARDEN_LANDSCHAP_EN_NATUUR?: number;
  NATUUR_1?: number;
  MAATSCHAPPELIJK?: number;
  BEDRIJF?: number;
  DETAILHANDEL?: number;
  BOS?: number;
  WONEN_GARAGES_EN_BERGINGEN?: number;
  BEDRIJF_NUTSVOORZIENING?: number;
  BEDRIJF_OPENBAAR_NUT?: number;
  VERKEER_RAILVERKEER?: number;
  DETAILHANDEL_TUINCENTRUM?: number;
  AGRARISCH?: number;
  AGRARISCH_MET_WAARDEN_LANDSCHAPPELIJKE_WAARDEN?: number;
  RECREATIE?: number;
  GEMENGD?: number;
  DIENSTVERLENING?: number;
  BEDRIJVENTERREIN?: number;
  BEDRIJF_2?: number;
  KANTOOR?: number;
  RECREATIE_DIERENVERBLIJF?: number;
  HORECA?: number;
  DETAILHANDEL_GROOTSCHALIG?: number;
  MAATSCHAPPELIJK_ONDERWIJSPARK?: number;
  SPORT_1?: number;
  CENTRUM?: number;
  MAATSCHAPPELIJK_ZORGCOMPLEX?: number;
  GEMENGD_WONENDIENSTVERLENING?: number;
  CULTUUR_EN_ONTSPANNING?: number;
  SPORT_2?: number;
  ARCHEOLOGIE_4?: number;
  MONUMENTAL?: number;
  HOOGSPANNING?: number;
  WATERKERING?: number;
  GAS?: number;
  ARCHEOLOGIE_5?: number;
  HOOGSPANNINGSVERBINDING?: number;
  ARCHEOLOGIE_6?: number;
  BOOM?: number;
  ARCHEOLOGIE_1?: number;
  ARCHEOLOGIE_3?: number;
  WATERBERGINGSGEBIED?: number;
  AARDGAS?: number;
  ARCHEOLOGIE_2?: number;
  BESCHERMD_STADSGEZICHT?: number;
  ARCHEOLOGIE?: number;
  BOUWVLAK?: number;
  BOUWVLAK_AGRARISCH_MET_WAARDEN_LANDSCHAPPELIJKE_WAARDEN?: number;
  BOUWVLAK_WONEN?: number;
  MAXIMUM_AANTAL_WOONEENHEDEN?: number;
  MAX_ROOF_GUTTER_HEIGHT?: number;
  MAX_BUILDING_HEIGHT?: number;
  MAXIMAAL_AANTAL_WOONEENHEDEN?: number;
  MINIMUM_AANTAL_PARKEERPLAATSEN?: number;
  MAXIMUM_DAKHELLING_GRADEN?: number;
  MINIMUM_DAKHELLING_GRADEN?: number;
  AANTAL?: number;
  MAXIMUM_BREEDTE_M?: number;
  MAX_BUILDING_PCT?: number;
  MAXIMUM_BEBOUWINGSPERCENTAGE?: number;
  BEDRIJF_AAN_HUIS?: number;
  INTENSIEVE_VEEHOUDERIJ?: number;
  ONTSLUITING_UITGESLOTEN?: number;
  SPECIFIEKE_VORM_VAN_BEDRIJF_GALERIE_EN_UITGEVERIJ?: number;
  WATERBERGING?: number;
  BEDRIJFSWONING?: number;
  SPECIFIEKE_VORM_VAN_DETAILHANDEL_1?: number;
  PARKEERTERREIN?: number;
  NUTSVOORZIENING?: number;
  SPECIFIEKE_VORM_VAN_BEDRIJF_HOUTVERWERKINGSBEDRIJF?: number;
  NUTSBEDRIJF?: number;
  ZORGINSTELLING?: number;
  WOONWAGENSTANDPLAATS?: number;
  VERKOOPPUNT_MOTORBRANDSTOFFEN_MET_LPG?: number;
  SPECIFIEKE_VORM_VAN_BEDRIJF_GEMEENTE_OPSLAG?: number;
  VOLKSTUIN?: number;
  ZORGWONING?: number;
  SUPERMARKT?: number;
  SPECIFIEKE_VORM_VAN_RECREATIE_MINIGOLF?: number;
  KINDERBOERDERIJ?: number;
  GEZONDHEIDSZORG?: number;
  SPORTHAL?: number;
  ZWEMBAD?: number;
  LAAD_EN_LOSPLAATS?: number;
  BEDRIJF_TOT_EN_MET_CATEGORIE_4?: number;
  SPECIFIEKE_VORM_VAN_DETAILHANDEL_2?: number;
  BEDRIJF_TOT_EN_MET_CATEGORIE_51?: number;
  SPECIFIEKE_VORM_VAN_BEDRIJF_ZANDWINNING?: number;
  BEGRAAFPLAATS?: number;
  SPECIFIEKE_VORM_VAN_WATER_BRUGWACHTERSHUISJE?: number;
  PRAKTIJKRUIMTE?: number;
  PARKEERGARAGE?: number;
  AANLEGSTEIGER?: number;
  SPECIFIEKE_VORM_VAN_WATER_WATERSPORT?: number;
  SPECIFIEKE_VORM_VAN_BEDRIJF_BETONWARENFABRIEK?: number;
  SPECIFIEKE_VORM_VAN_DETAILHANDEL_AUTOBEDRIJF?: number;
  SPECIFIEKE_VORM_VAN_BEDRIJF_AANHANGER_EN_OPLEGGERFABRIEK?: number;
  PARK?: number;
  SPECIFIEKE_VORM_VAN_VERKEER_FIETSENSTALLING?: number;
  SPECIFIEKE_VORM_VAN_MAATSCHAPPELIJK_KWEKERIJ?: number;
  HORECA_TOT_EN_MET_HORECACATEGORIE_3?: number;
  PARKEERTERREIN_UITGESLOTEN?: number;
  SPECIFIEKE_VORM_VAN_MAATSCHAPPELIJK_ONDERWIJSONDERSTEUNENDE_FUNCTIES?: number;
  SPECIFIEKE_VORM_VAN_VERKEER_KIOSK?: number;
  BIOSCOOP?: number;
  HORECA_TOT_EN_MET_HORECACATEGORIE_2?: number;
  TERRAS?: number;
  SPECIFIEKE_VORM_VAN_HORECA_KEUKEN?: number;
  SPECIFIEKE_VORM_VAN_CENTRUM_COFFEESHOP?: number;
  SPECIFIEKE_VORM_VAN_CENTRUM_AUTOMATENHAL?: number;
  KAMERVERHUUR?: number;
  HORECA_TOT_EN_MET_HORECACATEGORIE_4?: number;
  ZENDONTVANGSTINSTALLATIE?: number;
  SPECIFIEKE_VORM_VAN_WONEN_ZORGWONINGEN?: number;
  RAILVERKEER?: number;
  BEDRIJF_VAN_CATEGORIE_1?: number;
  BEDRIJF_TOT_EN_MET_CATEGORIE_3?: number;
  DANSSCHOOL?: number;
  SPECIFIEKE_VORM_VAN_CULTUUR_EN_ONTSPANNING_ZONNESTUDIO?: number;
  SPECIFIEKE_VORM_VAN_CULTUUR_EN_ONTSPANNING_OVERDEKTE_SPEELTUIN?: number;
  GRONDDEPOT?: number;
  SPOORWEG?: number;
  SPECIFIEKE_VORM_VAN_SPORT_DUIVENSPORTVERENIGING?: number;
  SPECIFIEKE_VORM_VAN_WONEN_WOONZORGGEBOUW?: number;
}
export interface NeighborhoodsFeatureProperties {
   ////****** */
   area:number
   _color:any;

   //**************/ */
  PERCENTAGE_GESCHEID?:                                number;
  HOTEL_GEMIDDELD_AANTAL_BINNEN_20_KM?:                number;
  PERCENTAGE_PERSONEN_0_TOT_15_JAAR?:                  number;
  STEDELIJKHEID_ADRESSEN_PER_KM_2:                     number;
  CAFE_GEMIDDELDE_AFSTAND_IN_KM?:                      number;
  GEBOORTE_TOTAAL:                                     number;
  GROTE_SUPERMARKT_GEMIDDELD_AANTAL_BINNEN_5_KM?:      number;
  PERCENTAGE_VERWEDUWD?:                               number;
  WINKELS_OV_DAGEL_LEVENSM_GEM_AANTAL_BINNEN_1_KM?:    number;
  DEKKINGSPERCENTAGE:                                  number;
  PERCENTAGE_PERSONEN_25_TOT_45_JAAR?:                 number;
  VOORTGEZET_ONDERWIJS_GEMIDDELD_AANTAL_BINNEN_3_KM?:  number;
  ID:                                                  number;
  PERCENTAGE_WESTERSE_MIGRATIEACHTERGROND?:            number;
  WARENHUIS_GEMIDDELDE_AFSTAND_IN_KM?:                 number;
  PERCENTAGE_PERSONEN_45_TOT_65_JAAR?:                 number;
  STERFTE_TOTAAL:                                      number;
  GEMIDDELDE_HUISHOUDSGROOTTE:                         number;
  MOTORTWEEWIELERS_TOTAAL:                             number;
  BUITENSCHOOLSE_OPVANG_GEMIDDELD_AANTAL_BINNEN_3_KM?: number;
  PERCENTAGE_LEEGSTAND_WONINGEN?:                      number;
  CAFETARIA_GEMIDDELD_AANTAL_BINNEN_3_KM?:             number;
  AANTAL_BEDRIJVEN_CULTUUR_RECREATIE_OVERIGE?:         number;
  PERCENTAGE_EENGEZINSWONING?:                         number;
  PERCENTAGE_KOOPWONINGEN?:                            number;
  KINDERDAGVERBLIJF_GEMIDDELDE_AFSTAND_IN_KM?:         number;
  ZONNEBANK_GEMIDDELDE_AFSTAND_IN_KM?:                 number;
  VMBO_GEMIDDELD_AANTAL_BINNEN_3_KM?:                  number;
  HOTEL_GEMIDDELD_AANTAL_BINNEN_5_KM?:                 number;
  ATTRACTIEPARK_GEMIDDELD_AANTAL_BINNEN_10_KM?:        number;
  PERCENTAGE_EENPERSOONSHUISHOUDENS?:                  number;
  VMBO_GEMIDDELD_AANTAL_BINNEN_10_KM?:                 number;
  HAVO_VWO_GEMIDDELD_AANTAL_BINNEN_10_KM?:             number;
  KUNSTIJSBAAN_GEMIDDELDE_AFSTAND_IN_KM?:              number;
  HUISARTSENPRAKTIJK_GEMIDDELDE_AFSTAND_IN_KM?:        number;
  PERSONENAUTOS_TOTAAL:                                number;
  AANTAL_BEDRIJVEN_NIJVERHEID_ENERGIE?:                number;
  PERSONENAUTOS_PER_HUISHOUDEN?:                       number;
  KINDERDAGVERBLIJF_GEMIDDELD_AANTAL_BINNEN_1_KM?:     number;
  PERCENTAGE_UIT_SURINAME?:                            number;
  BASISONDERWIJS_GEMIDDELD_AANTAL_BINNEN_5_KM?:        number;
  PERCENTAGE_ONGEHUWD?:                                number;
  PERCENTAGE_NIET_WESTERSE_MIGRATIEACHTERGROND?:       number;
  VOORTGEZET_ONDERWIJS_GEMIDDELD_AANTAL_BINNEN_5_KM?:  number;
  WINKELS_OV_DAGEL_LEVENSM_GEM_AANTAL_BINNEN_3_KM?:    number;
  CAFE_GEMIDDELD_AANTAL_BINNEN_1_KM?:                  number;
  AANTAL_PERSONENAUTOS_MET_OVERIGE_BRANDSTOF:          number;
  AANTAL_BEDRIJVEN_FINANCIEEL_ONROEREND_GOED?:         number;
  RESTAURANT_GEMIDDELD_AANTAL_BINNEN_5_KM?:            number;
  PERCENTAGE_UIT_NEDERLANDSE_ANTILLEN_EN_ARUBA?:       number;
  CAFETARIA_GEMIDDELDE_AFSTAND_IN_KM?:                 number;
  PERCENTAGE_BOUWJAARKLASSE_VANAF_2000?:               number;
  BUITENSCHOOLSE_OPVANG_GEMIDDELD_AANTAL_BINNEN_5_KM?: number;
  CAFETARIA_GEMIDDELD_AANTAL_BINNEN_5_KM?:             number;
  PERCENTAGE_PERSONEN_15_TOT_25_JAAR?:                 number;
  PERCENTAGE_HUURWONINGEN?:                            number;
  BIOSCOOP_GEMIDDELDE_AFSTAND_IN_KM?:                  number;
  RESTAURANT_GEMIDDELDE_AFSTAND_IN_KM?:                number;
  HAVO_VWO_GEMIDDELD_AANTAL_BINNEN_3_KM?:              number;
  INDELINGSWIJZIGING_WIJKEN_EN_BUURTEN:                number;
  HUISARTSENPRAKTIJK_GEMIDDELD_AANTAL_BINNEN_5_KM?:    number;
  BEVOLKINGSDICHTHEID_INWONERS_PER_KM_2?:              number;
  OPPERVLAKTE_WATER_IN_HA:                             number;
  PERC_HUURWONINGEN_IN_BEZIT_OVERIGE_VERHUURDERS?:     number;
  ATTRACTIEPARK_GEMIDDELD_AANTAL_BINNEN_50_KM?:        number;
  OPPERVLAKTE_LAND_IN_HA:                              number;
  WARENHUIS_GEMIDDELD_AANTAL_BINNEN_10_KM?:            number;
  BRANDWEERKAZERNE_GEMIDDELDE_AFSTAND_IN_KM?:          number;
  GEBOORTES_PER_1000_INWONERS:                         number;
  AANTAL_BEDRIJFSVESTIGINGEN:                          number;
  HAVO_VWO_GEMIDDELDE_AFSTAND_IN_KM?:                  number;
  JAAR:                                                number;
  PERCENTAGE_BOUWJAARKLASSE_TOT_2000?:                 number;
  PERCENTAGE_OVERIGE_NIETWESTERSEMIGRATIEACHTERGROND?: number;
  PERCENTAGE_HUISHOUDENS_ZONDER_KINDEREN?:             number;
  KINDERDAGVERBLIJF_GEMIDDELD_AANTAL_BINNEN_3_KM?:     number;
  BASISONDERWIJS_GEMIDDELD_AANTAL_BINNEN_3_KM?:        number;
  CAFE_GEMIDDELD_AANTAL_BINNEN_3_KM?:                  number;
  HOTEL_GEMIDDELD_AANTAL_BINNEN_10_KM?:                number;
  WINKELS_OV_DAGEL_LEVENSM_GEM_AANTAL_BINNEN_5_KM?:    number;
  AANTAL_BEDRIJVEN_VERVOER_INFORMATIE_COMMUNICATIE?:   number;
  INHABITANTS:                                         number;
  PERSONENAUTOS_PER_KM_2?:                             number;
  COLOR:                                               number;
  PERCENTAGE_BEWOOND?:                                 number;
  RESTAURANT_GEMIDDELD_AANTAL_BINNEN_3_KM?:            number;
  VROUWEN:                                             number;
  PERCENTAGE_WONINGEN_MET_EIGENDOM_ONBEKEND?:          number;
  MEEST_VOORKOMENDE_POSTCODE:                          number;
  PERCENTAGE_UIT_TURKIJE?:                             number;
  AANTAL_BEDRIJVEN_HANDEL_EN_HORECA?:                  number;
  WINKELS_OV_DAGELIJKSE_LEVENSM_GEM_AFST_IN_KM?:       number;
  BIOSCOOP_GEMIDDELD_AANTAL_BINNEN_10_KM?:             number;
  PERCENTAGE_PERSONEN_65_JAAR_EN_OUDER?:               number;
  GROTE_SUPERMARKT_GEMIDDELD_AANTAL_BINNEN_3_KM?:      number;
  AANTAL_INWONERS:                                     number;
  WARENHUIS_GEMIDDELD_AANTAL_BINNEN_5_KM?:             number;
  NAME:                                                string;
  HOTEL_GEMIDDELDE_AFSTAND_IN_KM?:                     number;
  PERCENTAGE_GEHUWD?:                                  number;
  AANTAL_BEDRIJVEN_LANDBOUW_BOSBOUW_VISSERIJ?:         number;
  AANTAL_PERSONENAUTOS_MET_BRANDSTOF_BENZINE:          number;
  GEMIDDELDE_WONINGWAARDE?:                            number;
  HUISARTSENPRAKTIJK_GEMIDDELD_AANTAL_BINNEN_3_KM?:    number;
  HAVO_VWO_GEMIDDELD_AANTAL_BINNEN_5_KM?:              number;
  SAUNA_GEMIDDELDE_AFSTAND_IN_KM?:                     number;
  BIBLIOTHEEK_GEMIDDELDE_AFSTAND_IN_KM?:               number;
  VOORTGEZET_ONDERWIJS_GEMIDDELD_AANTAL_BINNEN_10_KM?: number;
  PERCENTAGE_HUISHOUDENS_MET_KINDEREN?:                number;
  KINDERDAGVERBLIJF_GEMIDDELD_AANTAL_BINNEN_5_KM?:     number;
  VMBO_GEMIDDELDE_AFSTAND_IN_KM?:                      number;
  ATTRACTIEPARK_GEMIDDELDE_AFSTAND_IN_KM?:             number;
  ACTIVE:                                              number;
  BIOSCOOP_GEMIDDELD_AANTAL_BINNEN_5_KM?:              number;
  ZWEMBAD_GEMIDDELDE_AFSTAND_IN_KM?:                   number;
  ATTRACTIEPARK_GEMIDDELD_AANTAL_BINNEN_20_KM?:        number;
  PERCENTAGE_UIT_MAROKKO?:                             number;
  AANTAL_BEDRIJVEN_OVERHEID_ONDERWIJS_EN_ZORG?:        number;
  URBANIZATION:                                        number;
  AANTAL_BEDRIJVEN_ZAKELIJKE_DIENSTVERLENING?:         number;
  WONINGVOORRAAD:                                      number;
  CAFE_GEMIDDELD_AANTAL_BINNEN_5_KM?:                  number;
  BASISONDERWIJS_GEMIDDELD_AANTAL_BINNEN_1_KM?:        number;
  VOORTGEZET_ONDERWIJS_GEM_AFSTAND_IN_KM?:             number;
  BIOSCOOP_GEMIDDELD_AANTAL_BINNEN_20_KM?:             number;
  RESTAURANT_GEMIDDELD_AANTAL_BINNEN_1_KM?:            number;
  BASISONDERWIJS_GEMIDDELDE_AFSTAND_IN_KM?:            number;
  GROTE_SUPERMARKT_GEMIDDELDE_AFSTAND_IN_KM?:          number;
  OPPERVLAKTE_TOTAAL_IN_HA:                            number;
  MANNEN:                                              number;
  STERFTE_RELATIEF:                                    number;
  GROTE_SUPERMARKT_GEMIDDELD_AANTAL_BINNEN_1_KM?:      number;
  PERCENTAGE_MEERGEZINSWONING?:                        number;
  BUITENSCHOOLSE_OPVANG_GEM_AFSTAND_IN_KM?:            number;
  CAFETARIA_GEMIDDELD_AANTAL_BINNEN_1_KM?:             number;
  PERC_HUURWONINGEN_IN_BEZIT_WONINGCORPORATIES?:       number;
  BUITENSCHOOLSE_OPVANG_GEMIDDELD_AANTAL_BINNEN_1_KM?: number;
  OMGEVINGSADRESSENDICHTHEID:                          number;
  WARENHUIS_GEMIDDELD_AANTAL_BINNEN_20_KM?:            number;
  APOTHEEK_GEMIDDELDE_AFSTAND_IN_KM?:                  number;
  HUISARTSENPRAKTIJK_GEMIDDELD_AANTAL_BINNEN_1_KM?:    number;
  AANTAL_HUISHOUDENS:                                  number;
  VMBO_GEMIDDELD_AANTAL_BINNEN_5_KM?:                  number;
}
/// '["درصد_جدا_شده_است"," تعداد_متوسط_​​هتل_در_20_کیلومتری"," درصد_افراد_0_تا_15_سال"," آدرس_های_شهری_در_هر_کیلومتر_2"," فاصله_متوسط_​​کافه_در_کیلومتر"," کل_تولد"," تعداد_متوسط_​​سوپرمارکت_بزرگ_در_5_کیلومتری"," درصد_بیوه"," مغازه_ها_حمل_و_نقل_روز_از_زندگی_تعداد_متوسط_​​در_1_کیلومتر"," درصد_پوشش"," درصد_افراد_25_تا_45_سال"," تعداد_متوسط_​​آموزش_متوسطه_در_3_کیلومتر"," شناسه"," درصد_پیشینه_مهاجرت_به_غرب"," میانگین_فاصله_فروشگاه_در_کیلومتر"," درصد_افراد_45_تا_65_سال"," مرگ_و_میر_کل"," اندازه_متوسط_​​خانوار"," موتور_سیکلت_های_دو_چرخ_TOTAL"," تعداد_متوسط_​​مراقبت_در_خارج_از_مدرسه_در_3_کیلومتری"," درصد_خانه_های_خالی"," تعداد_متوسط_​​کافه_تریا_در_3_کیلومتری"," تعداد_شرکت_های_فرهنگی_تفریحی_دیگر"," درصد_مسکن_تک_خانواری"," درصد_خانه_های_برای_فروش"," متوسط_​​فاصله_مراقبت_از_کودکان_در_کیلومتر"," میانگین_فاصله_تخت_خورشیدی_بر_حسب_کیلومتر"," تعداد_میانگین_VMBO_در_3_کیلومتر"," تعداد_متوسط_​​هتل_در_5_کیلومتری"," تعداد_متوسط_​​در_10_کیلومتر"," درصد_خانوارهای_تک_نفره"," تعداد_میانگین_VMBO_در_10_کیلومتر"," تعداد_متوسط_​​HAVO_VWO_در_10_کیلومتر"," فاصله_متوسط_​​قفسه_مصنوعی_در_کیلومتر"," GP_میانگین_فاصله_در_کیلومتر_را_تمرین_کنید"," مجموع_وسایل_نقلیه_مسافری"," تعداد_شرکت_های_صنعت_انرژی"," خودروهای_مسافری_برای_هر_خانوار"," تعداد_متوسط_​​مراقبت_از_کودکان_در_1_کیلومتر"," درصد_از_سورینام"," تعداد_متوسط_​​آموزش_ابتدایی_در_5_کیلومتر"," درصد_متاهل_سازمان_ملل_متحد"," درصد_پیشینه_مهاجرت_غیرغربی"," تعداد_متوسط_​​آموزش_متوسطه_در_5_کیلومتر"," مغازه_ها_حمل_و_نقل_روز_از_زندگی_تعداد_متوسط_​​در_3_کیلومتر"," تعداد_متوسط_​​کافه_در_1_کیلومتر"," تعداد_وسایل_نقلیه_مسافری_با_سوخت_دیگر"," تعداد_مشاغل_مالی_املاک_و_مستغلات"," تعداد_متوسط_​​رستوران_در_5_کیلومتری"," درصد_از_آنتیل_هلند_و_آروبا"," فاصله_متوسط_​​کافه_تریا_در_کیلومتر"," درصد_کلاس_سال_ساخت_از_سال_2000"," تعداد_متوسط_​​مراقبت_در_خارج_از_مدرسه_در_5_کیلومتری"," تعداد_متوسط_​​کافه_تریا_در_5_کیلومتری"," درصد_افراد_15_تا_25_سال"," درصد_املاک_اجاره_ای"," میانگین_فاصله_سینما_بر_حسب_کیلومتر"," فاصله_متوسط_​​رستوران_در_کیلومتر"," تعداد_متوسط_​​HAVO_VWO_در_3_کیلومتر"," تغییر_چیدمان_منطقه_و_محله"," تعداد_متوسط_​​GP_را_در_5_کیلومتری_تمرین_کنید"," تراکم_جمعیت_ساکنان_در_هر_کیلومتر_2"," آب_سطحی_در_HA"," املاک_اجاره_ای_PERC_متعلق_به_زمین_داران_دیگر"," تعداد_متوسط_​​پارک_شگفت_انگیز_در_50_کیلومتری"," زمین_سطحی_در_HA"," میانگین_تعداد_فروشگاه_در_10_کیلومتر"," میانگین_فاصله_ایستگاه_آتش_نشانی_در_کیلومتر"," تولد_در_هر_1000_نفر"," تعداد_سایت_های_تجاری"," فاصله_متوسط_​​HAVO_VWO_در_کیلومتر"," سال"," درصد_کلاس_سال_ساخت_تا_سال_2000"," درصد_سایر_پیشینه_مهاجرت_غیرغربی"," درصد_خانوارهای_بدون_فرزند"," تعداد_متوسط_​​مراقبت_از_کودکان_در_3_کیلومتری"," تعداد_متوسط_​​آموزش_ابتدایی_در_3_کیلومتر"," تعداد_متوسط_​​کافه_در_3_کیلومتری"," تعداد_متوسط_​​هتل_در_10_K"]'
///'["PERCENTAGE_GESCHEID","HOTEL_GEMIDDELD_AANTAL_BINNEN_20_KM","PERCENTAGE_PERSONEN_0_TOT_15_JAAR","STEDELIJKHEID_ADRESSEN_PER_KM_2","CAFE_GEMIDDELDE_AFSTAND_IN_KM","GEBOORTE_TOTAAL","GROTE_SUPERMARKT_GEMIDDELD_AANTAL_BINNEN_5_KM","PERCENTAGE_VERWEDUWD","WINKELS_OV_DAGEL_LEVENSM_GEM_AANTAL_BINNEN_1_KM","DEKKINGSPERCENTAGE","PERCENTAGE_PERSONEN_25_TOT_45_JAAR","VOORTGEZET_ONDERWIJS_GEMIDDELD_AANTAL_BINNEN_3_KM","ID","PERCENTAGE_WESTERSE_MIGRATIEACHTERGROND","WARENHUIS_GEMIDDELDE_AFSTAND_IN_KM","PERCENTAGE_PERSONEN_45_TOT_65_JAAR","STERFTE_TOTAAL","GEMIDDELDE_HUISHOUDSGROOTTE","MOTORTWEEWIELERS_TOTAAL","BUITENSCHOOLSE_OPVANG_GEMIDDELD_AANTAL_BINNEN_3_KM","PERCENTAGE_LEEGSTAND_WONINGEN","CAFETARIA_GEMIDDELD_AANTAL_BINNEN_3_KM","AANTAL_BEDRIJVEN_CULTUUR_RECREATIE_OVERIGE","PERCENTAGE_EENGEZINSWONING","PERCENTAGE_KOOPWONINGEN","KINDERDAGVERBLIJF_GEMIDDELDE_AFSTAND_IN_KM","ZONNEBANK_GEMIDDELDE_AFSTAND_IN_KM","VMBO_GEMIDDELD_AANTAL_BINNEN_3_KM","HOTEL_GEMIDDELD_AANTAL_BINNEN_5_KM","ATTRACTIEPARK_GEMIDDELD_AANTAL_BINNEN_10_KM","PERCENTAGE_EENPERSOONSHUISHOUDENS","VMBO_GEMIDDELD_AANTAL_BINNEN_10_KM","HAVO_VWO_GEMIDDELD_AANTAL_BINNEN_10_KM","KUNSTIJSBAAN_GEMIDDELDE_AFSTAND_IN_KM","HUISARTSENPRAKTIJK_GEMIDDELDE_AFSTAND_IN_KM","PERSONENAUTOS_TOTAAL","AANTAL_BEDRIJVEN_NIJVERHEID_ENERGIE","PERSONENAUTOS_PER_HUISHOUDEN","KINDERDAGVERBLIJF_GEMIDDELD_AANTAL_BINNEN_1_KM","PERCENTAGE_UIT_SURINAME","BASISONDERWIJS_GEMIDDELD_AANTAL_BINNEN_5_KM","PERCENTAGE_ONGEHUWD","PERCENTAGE_NIET_WESTERSE_MIGRATIEACHTERGROND","VOORTGEZET_ONDERWIJS_GEMIDDELD_AANTAL_BINNEN_5_KM","WINKELS_OV_DAGEL_LEVENSM_GEM_AANTAL_BINNEN_3_KM","CAFE_GEMIDDELD_AANTAL_BINNEN_1_KM","AANTAL_PERSONENAUTOS_MET_OVERIGE_BRANDSTOF","AANTAL_BEDRIJVEN_FINANCIEEL_ONROEREND_GOED","RESTAURANT_GEMIDDELD_AANTAL_BINNEN_5_KM","PERCENTAGE_UIT_NEDERLANDSE_ANTILLEN_EN_ARUBA","CAFETARIA_GEMIDDELDE_AFSTAND_IN_KM","PERCENTAGE_BOUWJAARKLASSE_VANAF_2000","BUITENSCHOOLSE_OPVANG_GEMIDDELD_AANTAL_BINNEN_5_KM","CAFETARIA_GEMIDDELD_AANTAL_BINNEN_5_KM","PERCENTAGE_PERSONEN_15_TOT_25_JAAR","PERCENTAGE_HUURWONINGEN","BIOSCOOP_GEMIDDELDE_AFSTAND_IN_KM","RESTAURANT_GEMIDDELDE_AFSTAND_IN_KM","HAVO_VWO_GEMIDDELD_AANTAL_BINNEN_3_KM","INDELINGSWIJZIGING_WIJKEN_EN_BUURTEN","HUISARTSENPRAKTIJK_GEMIDDELD_AANTAL_BINNEN_5_KM","BEVOLKINGSDICHTHEID_INWONERS_PER_KM_2","OPPERVLAKTE_WATER_IN_HA","PERC_HUURWONINGEN_IN_BEZIT_OVERIGE_VERHUURDERS","ATTRACTIEPARK_GEMIDDELD_AANTAL_BINNEN_50_KM","OPPERVLAKTE_LAND_IN_HA","WARENHUIS_GEMIDDELD_AANTAL_BINNEN_10_KM","BRANDWEERKAZERNE_GEMIDDELDE_AFSTAND_IN_KM","GEBOORTES_PER_1000_INWONERS","AANTAL_BEDRIJFSVESTIGINGEN","HAVO_VWO_GEMIDDELDE_AFSTAND_IN_KM","JAAR","PERCENTAGE_BOUWJAARKLASSE_TOT_2000","PERCENTAGE_OVERIGE_NIETWESTERSEMIGRATIEACHTERGROND","PERCENTAGE_HUISHOUDENS_ZONDER_KINDEREN","KINDERDAGVERBLIJF_GEMIDDELD_AANTAL_BINNEN_3_KM","BASISONDERWIJS_GEMIDDELD_AANTAL_BINNEN_3_KM","CAFE_GEMIDDELD_AANTAL_BINNEN_3_KM","HOTEL_GEMIDDELD_AANTAL_BINNEN_10_K"]'
///`["PERCENTAGE_SEPARATED","HOTEL_AVERAGE_NUMBER_WITHIN_20_KM","PERCENTAGE_OF_PERSONS_0_TO_15_YEARS","URBAN_ADDRESSES_PER_KM_2","CAFE_AVERAGE_DISTANCE_IN_KM","BIRTH_TOTAL","LARGE_SUPERMARKET_AVERAGE_NUMBER_WITHIN_5_KM","PERCENTAGE_WIDOWED","SHOPS_TRANSPORT_DAY_OF_LIFE_AVERAGE_NUMBER_WITHIN_1_KM","COVERAGE_PERCENTAGE","PERCENTAGE_OF_PERSONS_25_TO_45_YEARS","SECONDARY_EDUCATION_AVERAGE_NUMBER_WITHIN_3_KM","ID","PERCENTAGE_OF_WESTERN_MIGRATION_BACKGROUND","DEPARTMENT_STORE_AVERAGE_DISTANCE_IN_KM","PERCENTAGE_OF_PERSONS_45_TO_65_YEARS","TOTAL_MORTALITY","AVERAGE_HOUSEHOLD_SIZE","TWO-WHEELED_MOTORCYCLES_TOTAL","OUTSIDE_SCHOOL_CARE_AVERAGE_NUMBER_WITHIN_3_KM","PERCENTAGE_OF_VACANT_HOUSES","CAFETERIA_AVERAGE_NUMBER_WITHIN_3_KM","NUMBER_OF_COMPANIES_CULTURE_RECREATION_OTHER","PERCENTAGE_OF_SINGLE-FAMILY_HOUSING","PERCENTAGE_OF_HOUSES_FOR_SALE","CHILDREN'S_CARE_AVERAGE_DISTANCE_IN_KM","SOLAR_BED_AVERAGE_DISTANCE_IN_KM","VMBO_AVERAGE_NUMBER_WITHIN_3_KM","HOTEL_AVERAGE_NUMBER_WITHIN_5_KM","AVERAGE_NUMBER_WITHIN_10_KM","PERCENTAGE_OF_SINGLE-PERSON_HOUSEHOLDS","VMBO_AVERAGE_NUMBER_WITHIN_10_KM","HAVO_VWO_AVERAGE_NUMBER_WITHIN_10_KM","ARTIFICIAL_RACK_AVERAGE_DISTANCE_IN_KM","GP_PRACTICE_AVERAGE_DISTANCE_IN_KM","PASSENGER_VEHICLES_TOTAL","NUMBER_OF_COMPANIES_INDUSTRY_ENERGY","PASSENGER_CARS_PER_HOUSEHOLD","CHILDREN'S_CARE_AVERAGE_NUMBER_WITHIN_1_KM","PERCENTAGE_FROM_SURINAME","PRIMARY_EDUCATION_AVERAGE_NUMBER_WITHIN_5_KM","PERCENTAGE_UN_MARRIED","PERCENTAGE_OF_NON-WESTERN_MIGRATION_BACKGROUND","SECONDARY_EDUCATION_AVERAGE_NUMBER_WITHIN_5_KM","SHOPS_TRANSPORT_DAY_OF_LIFE_AVERAGE_NUMBER_WITHIN_3_KM","CAFE_AVERAGE_NUMBER_WITHIN_1_KM","NUMBER_OF_PASSENGER_VEHICLES_WITH_OTHER_FUEL","NUMBER_OF_FINANCIAL_REAL_ESTATE_BUSINESSES","RESTAURANT_AVERAGE_NUMBER_WITHIN_5_KM","PERCENTAGE_FROM_THE_NETHERLANDS_ANTILLES_AND_ARUBA","CAFETERIA_AVERAGE_DISTANCE_IN_KM","PERCENTAGE_OF_BUILDING_YEAR_CLASS_FROM_2000","OUTSIDE_SCHOOL_CARE_AVERAGE_NUMBER_WITHIN_5_KM","CAFETERIA_AVERAGE_NUMBER_WITHIN_5_KM","PERCENTAGE_OF_PERSONS_15_TO_25_YEARS","PERCENTAGE_OF_RENTAL_PROPERTIES","CINEMA_AVERAGE_DISTANCE_IN_KM","RESTAURANT_AVERAGE_DISTANCE_IN_KM","HAVO_VWO_AVERAGE_NUMBER_WITHIN_3_KM","CHANGE_OF_LAYOUT_DISTRICT_AND_NEIGHBORHOODS","GP_PRACTICE_AVERAGE_NUMBER_WITHIN_5_KM","POPULATION_DENSITY_INHABITANTS_PER_KM_2","SURFACE_WATER_IN_HA","PERC_RENTAL_PROPERTIES_OWNED_BY_OTHER_LANDERS","AMAZING_PARK_AVERAGE_NUMBER_WITHIN_50_KM","SURFACE_LAND_IN_HA","DEPARTMENT_STORE_AVERAGE_NUMBER_WITHIN_10_KM","FIRE_STATION_AVERAGE_DISTANCE_IN_KM","BIRTH_PER_1000_INHABITANTS","NUMBER_OF_BUSINESS_SITES","HAVO_VWO_AVERAGE_DISTANCE_IN_KM","YEAR","PERCENTAGE_OF_BUILDING_YEAR_CLASS_UNTIL_2000","PERCENTAGE_OF_OTHER_NON-WESTERN_SEMIGRATION_BACKGROUND","PERCENTAGE_OF_HOUSEHOLDS_WITHOUT_CHILDREN","CHILDREN'S_CARE_AVERAGE_NUMBER_WITHIN_3_KM","PRIMARY_EDUCATION_AVERAGE_NUMBER_WITHIN_3_KM","CAFE_AVERAGE_NUMBER_WITHIN_3_KM","HOTEL_AVERAGE_NUMBER_WITHIN_10_K"]`

///tt =`[["PERCENTAGE_GESCHEID","PERCENTAGE_SEPARATED","درصد_جدا_شده_است"],["HOTEL_GEMIDDELD_AANTAL_BINNEN_20_KM","HOTEL_AVERAGE_NUMBER_WITHIN_20_KM"," تعداد_متوسط_​​هتل_در_20_کیلومتری"],["PERCENTAGE_PERSONEN_0_TOT_15_JAAR","PERCENTAGE_OF_PERSONS_0_TO_15_YEARS"," درصد_افراد_0_تا_15_سال"],["STEDELIJKHEID_ADRESSEN_PER_KM_2","URBAN_ADDRESSES_PER_KM_2"," آدرس_های_شهری_در_هر_کیلومتر_2"],["CAFE_GEMIDDELDE_AFSTAND_IN_KM","CAFE_AVERAGE_DISTANCE_IN_KM"," فاصله_متوسط_​​کافه_در_کیلومتر"],["GEBOORTE_TOTAAL","BIRTH_TOTAL"," کل_تولد"],["GROTE_SUPERMARKT_GEMIDDELD_AANTAL_BINNEN_5_KM","LARGE_SUPERMARKET_AVERAGE_NUMBER_WITHIN_5_KM"," تعداد_متوسط_​​سوپرمارکت_بزرگ_در_5_کیلومتری"],["PERCENTAGE_VERWEDUWD","PERCENTAGE_WIDOWED"," درصد_بیوه"],["WINKELS_OV_DAGEL_LEVENSM_GEM_AANTAL_BINNEN_1_KM","SHOPS_TRANSPORT_DAY_OF_LIFE_AVERAGE_NUMBER_WITHIN_1_KM"," مغازه_ها_حمل_و_نقل_روز_از_زندگی_تعداد_متوسط_​​در_1_کیلومتر"],["DEKKINGSPERCENTAGE","COVERAGE_PERCENTAGE"," درصد_پوشش"],["PERCENTAGE_PERSONEN_25_TOT_45_JAAR","PERCENTAGE_OF_PERSONS_25_TO_45_YEARS"," درصد_افراد_25_تا_45_سال"],["VOORTGEZET_ONDERWIJS_GEMIDDELD_AANTAL_BINNEN_3_KM","SECONDARY_EDUCATION_AVERAGE_NUMBER_WITHIN_3_KM"," تعداد_متوسط_​​آموزش_متوسطه_در_3_کیلومتر"],["ID","ID"," شناسه"],["PERCENTAGE_WESTERSE_MIGRATIEACHTERGROND","PERCENTAGE_OF_WESTERN_MIGRATION_BACKGROUND"," درصد_پیشینه_مهاجرت_به_غرب"],["WARENHUIS_GEMIDDELDE_AFSTAND_IN_KM","DEPARTMENT_STORE_AVERAGE_DISTANCE_IN_KM"," میانگین_فاصله_فروشگاه_در_کیلومتر"],["PERCENTAGE_PERSONEN_45_TOT_65_JAAR","PERCENTAGE_OF_PERSONS_45_TO_65_YEARS"," درصد_افراد_45_تا_65_سال"],["STERFTE_TOTAAL","TOTAL_MORTALITY"," مرگ_و_میر_کل"],["GEMIDDELDE_HUISHOUDSGROOTTE","AVERAGE_HOUSEHOLD_SIZE"," اندازه_متوسط_​​خانوار"],["MOTORTWEEWIELERS_TOTAAL","TWO-WHEELED_MOTORCYCLES_TOTAL"," موتور_سیکلت_های_دو_چرخ_TOTAL"],["BUITENSCHOOLSE_OPVANG_GEMIDDELD_AANTAL_BINNEN_3_KM","OUTSIDE_SCHOOL_CARE_AVERAGE_NUMBER_WITHIN_3_KM"," تعداد_متوسط_​​مراقبت_در_خارج_از_مدرسه_در_3_کیلومتری"],["PERCENTAGE_LEEGSTAND_WONINGEN","PERCENTAGE_OF_VACANT_HOUSES"," درصد_خانه_های_خالی"],["CAFETARIA_GEMIDDELD_AANTAL_BINNEN_3_KM","CAFETERIA_AVERAGE_NUMBER_WITHIN_3_KM"," تعداد_متوسط_​​کافه_تریا_در_3_کیلومتری"],["AANTAL_BEDRIJVEN_CULTUUR_RECREATIE_OVERIGE","NUMBER_OF_COMPANIES_CULTURE_RECREATION_OTHER"," تعداد_شرکت_های_فرهنگی_تفریحی_دیگر"],["PERCENTAGE_EENGEZINSWONING","PERCENTAGE_OF_SINGLE-FAMILY_HOUSING"," درصد_مسکن_تک_خانواری"],["PERCENTAGE_KOOPWONINGEN","PERCENTAGE_OF_HOUSES_FOR_SALE"," درصد_خانه_های_برای_فروش"],["KINDERDAGVERBLIJF_GEMIDDELDE_AFSTAND_IN_KM","CHILDREN'S_CARE_AVERAGE_DISTANCE_IN_KM"," متوسط_​​فاصله_مراقبت_از_کودکان_در_کیلومتر"],["ZONNEBANK_GEMIDDELDE_AFSTAND_IN_KM","SOLAR_BED_AVERAGE_DISTANCE_IN_KM"," میانگین_فاصله_تخت_خورشیدی_بر_حسب_کیلومتر"],["VMBO_GEMIDDELD_AANTAL_BINNEN_3_KM","VMBO_AVERAGE_NUMBER_WITHIN_3_KM"," تعداد_میانگین_VMBO_در_3_کیلومتر"],["HOTEL_GEMIDDELD_AANTAL_BINNEN_5_KM","HOTEL_AVERAGE_NUMBER_WITHIN_5_KM"," تعداد_متوسط_​​هتل_در_5_کیلومتری"],["ATTRACTIEPARK_GEMIDDELD_AANTAL_BINNEN_10_KM","AVERAGE_NUMBER_WITHIN_10_KM"," تعداد_متوسط_​​در_10_کیلومتر"],["PERCENTAGE_EENPERSOONSHUISHOUDENS","PERCENTAGE_OF_SINGLE-PERSON_HOUSEHOLDS"," درصد_خانوارهای_تک_نفره"],["VMBO_GEMIDDELD_AANTAL_BINNEN_10_KM","VMBO_AVERAGE_NUMBER_WITHIN_10_KM"," تعداد_میانگین_VMBO_در_10_کیلومتر"],["HAVO_VWO_GEMIDDELD_AANTAL_BINNEN_10_KM","HAVO_VWO_AVERAGE_NUMBER_WITHIN_10_KM"," تعداد_متوسط_​​HAVO_VWO_در_10_کیلومتر"],["KUNSTIJSBAAN_GEMIDDELDE_AFSTAND_IN_KM","ARTIFICIAL_RACK_AVERAGE_DISTANCE_IN_KM"," فاصله_متوسط_​​قفسه_مصنوعی_در_کیلومتر"],["HUISARTSENPRAKTIJK_GEMIDDELDE_AFSTAND_IN_KM","GP_PRACTICE_AVERAGE_DISTANCE_IN_KM"," GP_میانگین_فاصله_در_کیلومتر_را_تمرین_کنید"],["PERSONENAUTOS_TOTAAL","PASSENGER_VEHICLES_TOTAL"," مجموع_وسایل_نقلیه_مسافری"],["AANTAL_BEDRIJVEN_NIJVERHEID_ENERGIE","NUMBER_OF_COMPANIES_INDUSTRY_ENERGY"," تعداد_شرکت_های_صنعت_انرژی"],["PERSONENAUTOS_PER_HUISHOUDEN","PASSENGER_CARS_PER_HOUSEHOLD"," خودروهای_مسافری_برای_هر_خانوار"],["KINDERDAGVERBLIJF_GEMIDDELD_AANTAL_BINNEN_1_KM","CHILDREN'S_CARE_AVERAGE_NUMBER_WITHIN_1_KM"," تعداد_متوسط_​​مراقبت_از_کودکان_در_1_کیلومتر"],["PERCENTAGE_UIT_SURINAME","PERCENTAGE_FROM_SURINAME"," درصد_از_سورینام"],["BASISONDERWIJS_GEMIDDELD_AANTAL_BINNEN_5_KM","PRIMARY_EDUCATION_AVERAGE_NUMBER_WITHIN_5_KM"," تعداد_متوسط_​​آموزش_ابتدایی_در_5_کیلومتر"],["PERCENTAGE_ONGEHUWD","PERCENTAGE_UN_MARRIED"," درصد_متاهل_سازمان_ملل_متحد"],["PERCENTAGE_NIET_WESTERSE_MIGRATIEACHTERGROND","PERCENTAGE_OF_NON-WESTERN_MIGRATION_BACKGROUND"," درصد_پیشینه_مهاجرت_غیرغربی"],["VOORTGEZET_ONDERWIJS_GEMIDDELD_AANTAL_BINNEN_5_KM","SECONDARY_EDUCATION_AVERAGE_NUMBER_WITHIN_5_KM"," تعداد_متوسط_​​آموزش_متوسطه_در_5_کیلومتر"],["WINKELS_OV_DAGEL_LEVENSM_GEM_AANTAL_BINNEN_3_KM","SHOPS_TRANSPORT_DAY_OF_LIFE_AVERAGE_NUMBER_WITHIN_3_KM"," مغازه_ها_حمل_و_نقل_روز_از_زندگی_تعداد_متوسط_​​در_3_کیلومتر"],["CAFE_GEMIDDELD_AANTAL_BINNEN_1_KM","CAFE_AVERAGE_NUMBER_WITHIN_1_KM"," تعداد_متوسط_​​کافه_در_1_کیلومتر"],["AANTAL_PERSONENAUTOS_MET_OVERIGE_BRANDSTOF","NUMBER_OF_PASSENGER_VEHICLES_WITH_OTHER_FUEL"," تعداد_وسایل_نقلیه_مسافری_با_سوخت_دیگر"],["AANTAL_BEDRIJVEN_FINANCIEEL_ONROEREND_GOED","NUMBER_OF_FINANCIAL_REAL_ESTATE_BUSINESSES"," تعداد_مشاغل_مالی_املاک_و_مستغلات"],["RESTAURANT_GEMIDDELD_AANTAL_BINNEN_5_KM","RESTAURANT_AVERAGE_NUMBER_WITHIN_5_KM"," تعداد_متوسط_​​رستوران_در_5_کیلومتری"],["PERCENTAGE_UIT_NEDERLANDSE_ANTILLEN_EN_ARUBA","PERCENTAGE_FROM_THE_NETHERLANDS_ANTILLES_AND_ARUBA"," درصد_از_آنتیل_هلند_و_آروبا"],["CAFETARIA_GEMIDDELDE_AFSTAND_IN_KM","CAFETERIA_AVERAGE_DISTANCE_IN_KM"," فاصله_متوسط_​​کافه_تریا_در_کیلومتر"],["PERCENTAGE_BOUWJAARKLASSE_VANAF_2000","PERCENTAGE_OF_BUILDING_YEAR_CLASS_FROM_2000"," درصد_کلاس_سال_ساخت_از_سال_2000"],["BUITENSCHOOLSE_OPVANG_GEMIDDELD_AANTAL_BINNEN_5_KM","OUTSIDE_SCHOOL_CARE_AVERAGE_NUMBER_WITHIN_5_KM"," تعداد_متوسط_​​مراقبت_در_خارج_از_مدرسه_در_5_کیلومتری"],["CAFETARIA_GEMIDDELD_AANTAL_BINNEN_5_KM","CAFETERIA_AVERAGE_NUMBER_WITHIN_5_KM"," تعداد_متوسط_​​کافه_تریا_در_5_کیلومتری"],["PERCENTAGE_PERSONEN_15_TOT_25_JAAR","PERCENTAGE_OF_PERSONS_15_TO_25_YEARS"," درصد_افراد_15_تا_25_سال"],["PERCENTAGE_HUURWONINGEN","PERCENTAGE_OF_RENTAL_PROPERTIES"," درصد_املاک_اجاره_ای"],["BIOSCOOP_GEMIDDELDE_AFSTAND_IN_KM","CINEMA_AVERAGE_DISTANCE_IN_KM"," میانگین_فاصله_سینما_بر_حسب_کیلومتر"],["RESTAURANT_GEMIDDELDE_AFSTAND_IN_KM","RESTAURANT_AVERAGE_DISTANCE_IN_KM"," فاصله_متوسط_​​رستوران_در_کیلومتر"],["HAVO_VWO_GEMIDDELD_AANTAL_BINNEN_3_KM","HAVO_VWO_AVERAGE_NUMBER_WITHIN_3_KM"," تعداد_متوسط_​​HAVO_VWO_در_3_کیلومتر"],["INDELINGSWIJZIGING_WIJKEN_EN_BUURTEN","CHANGE_OF_LAYOUT_DISTRICT_AND_NEIGHBORHOODS"," تغییر_چیدمان_منطقه_و_محله"],["HUISARTSENPRAKTIJK_GEMIDDELD_AANTAL_BINNEN_5_KM","GP_PRACTICE_AVERAGE_NUMBER_WITHIN_5_KM"," تعداد_متوسط_​​GP_را_در_5_کیلومتری_تمرین_کنید"],["BEVOLKINGSDICHTHEID_INWONERS_PER_KM_2","POPULATION_DENSITY_INHABITANTS_PER_KM_2"," تراکم_جمعیت_ساکنان_در_هر_کیلومتر_2"],["OPPERVLAKTE_WATER_IN_HA","SURFACE_WATER_IN_HA"," آب_سطحی_در_HA"],["PERC_HUURWONINGEN_IN_BEZIT_OVERIGE_VERHUURDERS","PERC_RENTAL_PROPERTIES_OWNED_BY_OTHER_LANDERS"," املاک_اجاره_ای_PERC_متعلق_به_زمین_داران_دیگر"],["ATTRACTIEPARK_GEMIDDELD_AANTAL_BINNEN_50_KM","AMAZING_PARK_AVERAGE_NUMBER_WITHIN_50_KM"," تعداد_متوسط_​​پارک_شگفت_انگیز_در_50_کیلومتری"],["OPPERVLAKTE_LAND_IN_HA","SURFACE_LAND_IN_HA"," زمین_سطحی_در_HA"],["WARENHUIS_GEMIDDELD_AANTAL_BINNEN_10_KM","DEPARTMENT_STORE_AVERAGE_NUMBER_WITHIN_10_KM"," میانگین_تعداد_فروشگاه_در_10_کیلومتر"],["BRANDWEERKAZERNE_GEMIDDELDE_AFSTAND_IN_KM","FIRE_STATION_AVERAGE_DISTANCE_IN_KM"," میانگین_فاصله_ایستگاه_آتش_نشانی_در_کیلومتر"],["GEBOORTES_PER_1000_INWONERS","BIRTH_PER_1000_INHABITANTS"," تولد_در_هر_1000_نفر"],["AANTAL_BEDRIJFSVESTIGINGEN","NUMBER_OF_BUSINESS_SITES"," تعداد_سایت_های_تجاری"],["HAVO_VWO_GEMIDDELDE_AFSTAND_IN_KM","HAVO_VWO_AVERAGE_DISTANCE_IN_KM"," فاصله_متوسط_​​HAVO_VWO_در_کیلومتر"],["JAAR","YEAR"," سال"],["PERCENTAGE_BOUWJAARKLASSE_TOT_2000","PERCENTAGE_OF_BUILDING_YEAR_CLASS_UNTIL_2000"," درصد_کلاس_سال_ساخت_تا_سال_2000"],["PERCENTAGE_OVERIGE_NIETWESTERSEMIGRATIEACHTERGROND","PERCENTAGE_OF_OTHER_NON-WESTERN_SEMIGRATION_BACKGROUND"," درصد_سایر_پیشینه_مهاجرت_غیرغربی"],["PERCENTAGE_HUISHOUDENS_ZONDER_KINDEREN","PERCENTAGE_OF_HOUSEHOLDS_WITHOUT_CHILDREN"," درصد_خانوارهای_بدون_فرزند"],["KINDERDAGVERBLIJF_GEMIDDELD_AANTAL_BINNEN_3_KM","CHILDREN'S_CARE_AVERAGE_NUMBER_WITHIN_3_KM"," تعداد_متوسط_​​مراقبت_از_کودکان_در_3_کیلومتری"],["BASISONDERWIJS_GEMIDDELD_AANTAL_BINNEN_3_KM","PRIMARY_EDUCATION_AVERAGE_NUMBER_WITHIN_3_KM"," تعداد_متوسط_​​آموزش_ابتدایی_در_3_کیلومتر"],["CAFE_GEMIDDELD_AANTAL_BINNEN_3_KM","CAFE_AVERAGE_NUMBER_WITHIN_3_KM"," تعداد_متوسط_​​کافه_در_3_کیلومتری"],["HOTEL_GEMIDDELD_AANTAL_BINNEN_10_K","HOTEL_AVERAGE_NUMBER_WITHIN_10_K"," تعداد_متوسط_​​هتل_در_10_K"]]`
export enum Permitter {
  GemeenteMeppel = 'Gemeente Meppel',
  GemeenteStaphorst = 'Gemeente Staphorst',
}
