name: mepple geo App workflow 
on:
    workflow_dispatch:
    push:
        tags:
            - v**

permissions:
    contents: read
    pages: write
    id-token: write


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: build angular
              run: npm run ng build
            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: dist
                path: ./dist/geo-app-test 





            

  
