name: mepple geo App workflow 
on:
    workflow_dispatch:
    push:
        tags:
            - v**
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: build angular
              run: npm run ng build


            

  
